
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FichiersAction;

	private global::Gtk.Action FichierAction;

	private global::Gtk.Action AideAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.Notebook notebook2;

	private global::Gtk.VPaned vpaned1;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TreeView treeview2;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.HSeparator hseparator2;

	private global::Gtk.Label GtkLabel4;

	private global::Gtk.Frame frame3;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.NodeView nodeview1;

	private global::Gtk.VBox vbox3;

	private global::Gtk.ComboBox combobox1;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.HSeparator hseparator3;

	private global::Gtk.Label GtkLabel6;

	private global::Gtk.Label label2;

	private global::Gtk.Label label3;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FichiersAction = new global::Gtk.Action("FichiersAction", global::Mono.Unix.Catalog.GetString("Fichiers"), null, null);
		this.FichiersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Fichiers");
		w1.Add(this.FichiersAction, null);
		this.FichierAction = new global::Gtk.Action("FichierAction", global::Mono.Unix.Catalog.GetString("Fichier"), null, null);
		this.FichierAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Fichier");
		w1.Add(this.FichierAction, null);
		this.AideAction = new global::Gtk.Action("AideAction", global::Mono.Unix.Catalog.GetString("Aide"), null, null);
		this.AideAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Aide");
		w1.Add(this.AideAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Mic");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-record", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'FichierAction\' action=\'FichierAction\'/><" +
				"menu name=\'AideAction\' action=\'AideAction\'/></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook2 = new global::Gtk.Notebook();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.vpaned1 = new global::Gtk.VPaned();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 190;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.frame2 = new global::Gtk.Frame();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview2 = new global::Gtk.TreeView();
		this.treeview2.CanFocus = true;
		this.treeview2.Name = "treeview2";
		this.GtkScrolledWindow.Add(this.treeview2);
		this.hbox1.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w4.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.Text = global::Mono.Unix.Catalog.GetString("Nom prénom");
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox2.Add(this.entry1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entry1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button1 = new global::Gtk.Button();
		this.button1.Sensitive = false;
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString("Ajouter un élève");
		global::Gtk.Image w6 = new global::Gtk.Image();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
		this.button1.Image = w6;
		this.vbox2.Add(this.button1);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button1]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button();
		this.button2.Sensitive = false;
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString("Supprimer");
		global::Gtk.Image w8 = new global::Gtk.Image();
		w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
		this.button2.Image = w8;
		this.vbox2.Add(this.button2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.button2]));
		w9.PackType = ((global::Gtk.PackType)(1));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hseparator2 = new global::Gtk.HSeparator();
		this.hseparator2.Name = "hseparator2";
		this.vbox2.Add(this.hseparator2);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator2]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 3;
		w10.Expand = false;
		w10.Fill = false;
		this.hbox1.Add(this.vbox2);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
		w11.Position = 1;
		w11.Expand = false;
		this.GtkAlignment.Add(this.hbox1);
		this.frame2.Add(this.GtkAlignment);
		this.GtkLabel4 = new global::Gtk.Label();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Exercice en cours : Exercice 1</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.vpaned1.Add(this.frame2);
		global::Gtk.Paned.PanedChild w14 = ((global::Gtk.Paned.PanedChild)(this.vpaned1[this.frame2]));
		w14.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.frame3 = new global::Gtk.Frame();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.nodeview1 = new global::Gtk.NodeView();
		this.nodeview1.CanFocus = true;
		this.nodeview1.Name = "nodeview1";
		this.GtkScrolledWindow1.Add(this.nodeview1);
		this.hbox2.Add(this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.GtkScrolledWindow1]));
		w16.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.combobox1 = global::Gtk.ComboBox.NewText();
		this.combobox1.Name = "combobox1";
		this.vbox3.Add(this.combobox1);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.combobox1]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.Sensitive = false;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Importer une piste");
		global::Gtk.Image w18 = new global::Gtk.Image();
		w18.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-go-down", global::Gtk.IconSize.Menu);
		this.button3.Image = w18;
		this.vbox3.Add(this.button3);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button3]));
		w19.Position = 1;
		w19.Expand = false;
		w19.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.Sensitive = false;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Supprimer");
		global::Gtk.Image w20 = new global::Gtk.Image();
		w20.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
		this.button4.Image = w20;
		this.vbox3.Add(this.button4);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.button4]));
		w21.PackType = ((global::Gtk.PackType)(1));
		w21.Position = 2;
		w21.Expand = false;
		w21.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hseparator3 = new global::Gtk.HSeparator();
		this.hseparator3.Name = "hseparator3";
		this.vbox3.Add(this.hseparator3);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hseparator3]));
		w22.PackType = ((global::Gtk.PackType)(1));
		w22.Position = 3;
		w22.Expand = false;
		w22.Fill = false;
		this.hbox2.Add(this.vbox3);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox3]));
		w23.Position = 1;
		w23.Expand = false;
		w23.Fill = false;
		this.GtkAlignment3.Add(this.hbox2);
		this.frame3.Add(this.GtkAlignment3);
		this.GtkLabel6 = new global::Gtk.Label();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Fichiers en attente d\'import</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel6;
		this.vpaned1.Add(this.frame3);
		this.notebook2.Add(this.vpaned1);
		// Notebook tab
		this.label2 = new global::Gtk.Label();
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Exercice en cours");
		this.notebook2.SetTabLabel(this.vpaned1, this.label2);
		this.label2.ShowAll();
		// Notebook tab
		global::Gtk.Label w28 = new global::Gtk.Label();
		w28.Visible = true;
		this.notebook2.Add(w28);
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Archives");
		this.notebook2.SetTabLabel(w28, this.label3);
		this.label3.ShowAll();
		// Notebook tab
		global::Gtk.Label w29 = new global::Gtk.Label();
		w29.Visible = true;
		this.notebook2.Add(w29);
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Corbeille");
		this.notebook2.SetTabLabel(w29, this.label1);
		this.label1.ShowAll();
		this.vbox1.Add(this.notebook2);
		global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook2]));
		w30.Position = 1;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 504;
		this.DefaultHeight = 435;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
