
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FichiersAction;

	private global::Gtk.Action FichierAction;

	private global::Gtk.Action AideAction;

	private global::Gtk.Action addAction;

	private global::Gtk.Action editAction;

	private global::Gtk.ToggleAction helpAction;

	private global::Gtk.RadioAction newAction;

	private global::Gtk.Action openAction;

	private global::Gtk.VBox vboxMain;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.NodeView exercicesListView;

	private global::Gtk.HBox hboxButtons;

	private global::Gtk.HButtonBox hbuttonbox1;

	private global::Gtk.Button newExerciceButton;

	private global::Gtk.Button editExerciceButton;

	private global::Gtk.Button openExercicesInExplorerButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.FichiersAction = new global::Gtk.Action("FichiersAction", global::Mono.Unix.Catalog.GetString("Fichiers"), null, null);
		this.FichiersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Fichiers");
		w1.Add(this.FichiersAction, null);
		this.FichierAction = new global::Gtk.Action("FichierAction", global::Mono.Unix.Catalog.GetString("Fichier"), null, null);
		this.FichierAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Fichier");
		w1.Add(this.FichierAction, null);
		this.AideAction = new global::Gtk.Action("AideAction", global::Mono.Unix.Catalog.GetString("Aide"), null, null);
		this.AideAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Aide");
		w1.Add(this.AideAction, null);
		this.addAction = new global::Gtk.Action("addAction", null, null, "gtk-add");
		w1.Add(this.addAction, null);
		this.editAction = new global::Gtk.Action("editAction", null, null, "gtk-edit");
		this.editAction.Sensitive = false;
		w1.Add(this.editAction, null);
		this.helpAction = new global::Gtk.ToggleAction("helpAction", null, null, "gtk-help");
		w1.Add(this.helpAction, null);
		this.newAction = new global::Gtk.RadioAction("newAction", null, null, "gtk-new", 0);
		this.newAction.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		w1.Add(this.newAction, null);
		this.openAction = new global::Gtk.Action("openAction", null, null, "gtk-open");
		w1.Add(this.openAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Mic");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-record", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vboxMain = new global::Gtk.VBox();
		this.vboxMain.Name = "vboxMain";
		this.vboxMain.Spacing = 6;
		this.vboxMain.BorderWidth = ((uint)(20));
		// Container child vboxMain.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.exercicesListView = new global::Gtk.NodeView();
		this.exercicesListView.CanFocus = true;
		this.exercicesListView.Name = "exercicesListView";
		this.GtkScrolledWindow.Add(this.exercicesListView);
		this.vboxMain.Add(this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.GtkScrolledWindow]));
		w3.Position = 0;
		// Container child vboxMain.Gtk.Box+BoxChild
		this.hboxButtons = new global::Gtk.HBox();
		this.hboxButtons.Name = "hboxButtons";
		this.hboxButtons.Spacing = 6;
		// Container child hboxButtons.Gtk.Box+BoxChild
		this.hbuttonbox1 = new global::Gtk.HButtonBox();
		this.hbuttonbox1.Name = "hbuttonbox1";
		this.hbuttonbox1.Spacing = 20;
		this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.newExerciceButton = new global::Gtk.Button();
		this.newExerciceButton.CanFocus = true;
		this.newExerciceButton.Name = "newExerciceButton";
		this.newExerciceButton.UseUnderline = true;
		this.newExerciceButton.Label = global::Mono.Unix.Catalog.GetString("Nouvel exercice");
		global::Gtk.Image w4 = new global::Gtk.Image();
		w4.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-add", global::Gtk.IconSize.Menu);
		this.newExerciceButton.Image = w4;
		this.hbuttonbox1.Add(this.newExerciceButton);
		global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.newExerciceButton]));
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.editExerciceButton = new global::Gtk.Button();
		this.editExerciceButton.Sensitive = false;
		this.editExerciceButton.CanFocus = true;
		this.editExerciceButton.Name = "editExerciceButton";
		this.editExerciceButton.UseUnderline = true;
		this.editExerciceButton.Label = global::Mono.Unix.Catalog.GetString("Reprendre cet exercice");
		global::Gtk.Image w6 = new global::Gtk.Image();
		w6.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
		this.editExerciceButton.Image = w6;
		this.hbuttonbox1.Add(this.editExerciceButton);
		global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.editExerciceButton]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.hboxButtons.Add(this.hbuttonbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.hbuttonbox1]));
		w8.Position = 0;
		// Container child hboxButtons.Gtk.Box+BoxChild
		this.openExercicesInExplorerButton = new global::Gtk.Button();
		this.openExercicesInExplorerButton.CanFocus = true;
		this.openExercicesInExplorerButton.Name = "openExercicesInExplorerButton";
		this.openExercicesInExplorerButton.UseUnderline = true;
		this.openExercicesInExplorerButton.Label = global::Mono.Unix.Catalog.GetString("Voir dans l\'explorateur");
		global::Gtk.Image w9 = new global::Gtk.Image();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-directory", global::Gtk.IconSize.Menu);
		this.openExercicesInExplorerButton.Image = w9;
		this.hboxButtons.Add(this.openExercicesInExplorerButton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.openExercicesInExplorerButton]));
		w10.PackType = ((global::Gtk.PackType)(1));
		w10.Position = 1;
		w10.Expand = false;
		w10.Fill = false;
		this.vboxMain.Add(this.hboxButtons);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hboxButtons]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.Add(this.vboxMain);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 570;
		this.DefaultHeight = 435;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
