
// This file has been generated by the GUI designer. Do not modify.
namespace Mic
{
	public partial class ImportWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview2;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button button308;

		private global::Gtk.Button button307;

		private global::Gtk.ComboBoxEntry comboboxentry1;

		private global::Gtk.ComboBoxEntry comboboxentry2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Mic.ImportWindow
			this.Name = "Mic.ImportWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Mic - Importer des fichiers depuis le microphone");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-media-record", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(20));
			// Container child Mic.ImportWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview2 = new global::Gtk.NodeView();
			this.nodeview2.CanFocus = true;
			this.nodeview2.Name = "nodeview2";
			this.GtkScrolledWindow.Add(this.nodeview2);
			this.vbox4.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button308 = new global::Gtk.Button();
			this.button308.CanFocus = true;
			this.button308.Name = "button308";
			this.button308.UseUnderline = true;
			this.button308.Label = global::Mono.Unix.Catalog.GetString("Vider le micro");
			this.hbox2.Add(this.button308);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button308]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button307 = new global::Gtk.Button();
			this.button307.CanFocus = true;
			this.button307.Name = "button307";
			this.button307.UseUnderline = true;
			this.button307.Label = global::Mono.Unix.Catalog.GetString("Importer");
			this.hbox2.Add(this.button307);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button307]));
			w4.PackType = ((global::Gtk.PackType)(1));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboboxentry1 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry1.AppendText(global::Mono.Unix.Catalog.GetString("Nom de l\'élève"));
			this.comboboxentry1.CanDefault = true;
			this.comboboxentry1.Name = "comboboxentry1";
			this.comboboxentry1.Active = 0;
			this.hbox2.Add(this.comboboxentry1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboboxentry1]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.comboboxentry2 = global::Gtk.ComboBoxEntry.NewText();
			this.comboboxentry2.AppendText(global::Mono.Unix.Catalog.GetString("Nom de l\'exercice"));
			this.comboboxentry2.Name = "comboboxentry2";
			this.comboboxentry2.Active = 0;
			this.hbox2.Add(this.comboboxentry2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.comboboxentry2]));
			w6.PackType = ((global::Gtk.PackType)(1));
			w6.Position = 3;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox4.Add(this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 571;
			this.DefaultHeight = 328;
			this.comboboxentry1.HasDefault = true;
			this.Show();
		}
	}
}
